### PR TITLE
Added for each mut to iterate on the stored iterms

### PR DESCRIPTION
**Pull request by AndreaCatania**
Added a for each function that iterate over all the elements, mutably.

Unfortunately the `pop_access` function work using `&mut self`, but would have be really really useful iterate over the items immutably to just check these.

I'm open to suggestion.

### CODE REVIEW

**Comment by AndreaCatania** [comment]
Also, executed `cargo fmt`

**Comment by agerasev** [comment]
Hi! Thank you for your contribution!
I agree that `for_each_mut` method for the `Consumer` is useful, and it seems to be safe because it has exclusive write access to the elements being iterated. Maybe it would be useful to add a similar `for_each` method for immutable access?

**Comment by agerasev** [comment]
Also thanks for the formatting. But maybe it would be reasonable to make this in separate commit to avoid confusion by such large diff?

**Comment by agerasev** [comment]
FYI for now I'm working on the next version of the ring buffer: https://github.com/agerasev/ringbuf/tree/dev0.2. There are some changes and improvements, but the main change is wrapping the buffer content in [`MaybeUninit<T>`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html) because uninitialized data without this wrapper cause undefined behavior with newer compilers.
I'll consider to add `for_each*` methods to this next version of `ringbuf`.

**Comment by AndreaCatania** [comment]
Mice to hear that you are working on the version 2. Regarding the immutable `for_each` would be necessary have a `pop_access` that uses immutable `self`. I didn't create it because I prefer that you say your opinion about it, first.

I'm going to split the `cargo fmt` with the actual code change.

**Comment by AndreaCatania** [comment]
I split the two commits and added new one that solve two minor `cargo clippy` warnings.

---
Regarding `cargo clippy`, it keep complain about this function:

```
unsafe fn get_mut(&self) -> &mut Vec<T> {
    self.cell.get().as_mut().unwrap()
}
```

I saw that this function is used by `push_access` and `pop_access` which both use `&mut self`. This mean that this function can be converted without any problem to:

```
fn get_mut(&mut self) -> &mut Vec<T> {
    self.cell.get().as_mut().unwrap()
}
```
---
### Multi thread question

I saw that this buffer can be already sent between threads, thanks to the `AtomicUsize` that allow you to keep things tidy.
Everything is fine since actually you can just push and pop elements from the memory, but if you want to expand the feature of this buffer I think that you have to address few things.

By using interior mutability (directly inside the buffer), each time that you need to touch the memory, even for just read what's inside (see the `for_each`), you need to block all the other threads.

(So you can't have multiple threads that just read what's inside)

To fix this problem, I proposed is to:
- Remove the `AtomicUsize` and use a simple `usize`.
- Change `push_access` to `push_access_mut`.
- Change `pop_access` to `pop_access_mut`.
- Add the immutable version of `pop_access` that allows to read the memory with immutable `self`.

At this point, you are using the borrow checker to handle the mutability, and to send it through threads you will wrap the buffer with a `Arc<Rc<>>` that will restore interior mutability.

The result will be a crate with:
- A lot less unsafe code.
- Usable in single thread without boring interior mutability.
- Will allow the user to define the interior mutability rules, that most fits its needs, by using `Rc` or `Mutex` or `unsafe`, etc... .

Note: *I would really need to read the content of the buffer in multi thread, without blocking each thread just to read its content.*

**Comment by AndreaCatania** [comment]
(If you are ok with this change, I'm available to help you by doing it or doing part of it)

**Comment by agerasev** [comment]
Oh, there is so much to discuss. I'll answer in multiple messages.

**Comment by agerasev** [comment]
About the `cargo clippy` message. It tells about this method:
https://github.com/agerasev/ringbuf/blob/869b574ae374476c5a0278371e25863efa9cec4b/src/lib.rs#L225-L227
This method belongs to `SharedVec` structure. The purpose of this structure is to provide multiple mutable access to the same memory. `SharedVec` is stored inside of `RingBuffer` which, in turn, is wrapped by `Arc`. `Arc` (without `Mutex`) cannot provide mutable access to its content, so we cannot access `SharedVec` mutably. For this reason `get_mut` takes `&self` not `&mut self`.

**Comment by agerasev** [comment]
I fully agree with the usefullness of immutable version of `pop_access` and I'm ready to add it to the implementation. But I would like not to break the backward compatibility with the `v0.1`, so I suggest not to rename `pop_access`, but to name these new methods `access` and `access_mut` respectively (without using word `pop`, because they don't actually pop elements, just access them).

**Comment by agerasev** [comment]
Now about multi-threading question.

If I understand right, you need to have multiple consumers in different threads which should be available to immutably access the content of the ring buffer. If so, there is a straightforward solution, as it seems to me: we can create `Arc<Consumer>` and send it to all these threads. `Arc` provides immutable access to its content, so we are able to call immutable `access`.

But here is a problem. As long as we have more than one instance of `Arc<Consumer>`, we cannot access this consumer mutably, for example, we cannot pop elements out of it. To get mutable access to it again (without `Mutex` or `RwLock`) we should make all threads to drop their `Arc`'s except one, and `try_unwrap` the remaining one back to `Consumer`. And as far as I know, this is the general issue of cuncurrency, not only of this implementation.

**Comment by AndreaCatania** [comment]
Basically my idea is to simplify the implementation of this ring buffer by removing the interior mutability and so the unsafe blocks. Where the functions like push / pop will use `&mut self`, all others like the `for_each` will use `&self`.

By doing so, the naked `RingBuffer` will not be able to be sent to multi thread, and will require to be wrapped on a `RwLock` / `Mutex` / `etc...`.

In this way the implementation will be much simple, but most important safe; the Multi thread problem mentioned above will be solved by the, already solid, rust atomic wrappers; the users can adapt this class more naturally depending on their context (without the needs for this crate to provide a specific implementation [see my request]).

---

However, I agree that not break the compatibility would be better, but I would prefer to break it in favor of API clarity.
If this is your main big concern, what do you thing about create a new crate (something like: RingBuff-Next) that have (few of them) different APIs?

**Comment by agerasev** [comment]
Further about https://github.com/agerasev/ringbuf/pull/3#issuecomment-551421513.

Sorry, I cannot fully understand the idea of your proposal. Do you suggest to make ring buffer unsynchronized and single-threaded only (i.e. by removing atomics) and shift to a user the responsibility of synchronizing it between threads?
The main idea of this crate is to hide synchronization issues and access to uninitialized memory inside producer and consumer implementation (well, not fully, there are methods like `pop_access`, but this is a tradeoff between safety and flexibility, and these methods are unsafe so you should use them wisely). This ring buffer is only SPSC because it's a challenge to implement a non-blocking ring buffer with multiple producers or consumers.

**Comment by AndreaCatania** [comment]
hmm, I see the issue with my proposal.

**Comment by AndreaCatania** [comment]
So the idea is to wrap the `Consumer` in this way: `Arc<RwLock<Consumer>>`. It will allow me to read the data (immutably) without blocking any threads, and blocking the threads while popoing out the data.

By doing so, the readers may not read the same data because the `Producer` is non blocking, but I think that it's ok. Thanks for the clarification.

**Comment by AndreaCatania** [comment]
Added another commit to suppress the clippy warning on the `unsafe fn get_mut(&self) -> &mut Vec<T> { `

**Comment by agerasev** [comment]
> So the idea is to wrap the `Consumer` in this way: `Arc<RwLock<Consumer>>`. It will allow me to read the data (immutably) without blocking any threads, and blocking the threads while popoing out the data.

Nice idea! It seems to solve your problem.
 
> By doing so, the readers may not read the same data because the `Producer` is non blocking, but I think that it's ok. Thanks for the clarification.

All right, `Producer` and `Consumer` don't have to exclusively block each other, because they're designed to be non-blocking. You're welcome!

I'll merge your commits soon. Thanks for your work!

**Comment by agerasev** [comment]
I've added `access`, `access_mut` methods for safe access to buffer content, and `for_each` method for immutable iteration over buffer elements.
Also I've published this new version on [crates.io](https://crates.io/crates/ringbuf).

Thank you very much for your contribution!

**Comment by AndreaCatania** [comment]
Awesome, thanks!

**Pull request merged**
